/**
 * Afiya Leathers — full SHOP category tree seed
 * Run: node seeds/seedAfiyaCategories.js
 */

export const AFIYA_CATEGORY_TREE = [
  {
    name: "Men",
    slug: "men",
    type: "department",
    gender: "men",
    order: 1,
    children: [
      "Leather Jackets",
      "Suede Jackets",
      "Leather Blazers",
      "Leather Shirts",
      "Leather Pants",
      "Leather Shorts",
      "Leather Trench Coats",
      "Leather Vest Coats",
      "Leather Jumpsuits",
      "Leather Aprons",
    ],
  },
  {
    name: "Women",
    slug: "women",
    type: "department",
    gender: "women",
    order: 2,
    children: [
      "Leather Jackets",
      "Suede Jackets",
      "Leather Blazers",
      "Leather Dresses",
      "Leather Tops",
      "Leather Shirts",
      "Leather Pants",
      "Leather Shorts",
      "Leather Skirts",
      "Leather Trench Coats",
      "Leather Vest Coats",
      "Leather Jumpsuits",
      "Leather Aprons",
    ],
  },
  {
    name: "Bags",
    slug: "bags",
    type: "department",
    order: 3,
    children: [
      {
        name: "Men's Bags",
        slug: "mens-bags",
        type: "group",
        gender: "men",
        children: [
          "Office Bags",
          "Laptop Bags",
          "Messenger Bags",
          "Backpacks",
          "Sling Bags",
        ],
      },
      {
        name: "Women's Bags",
        slug: "womens-bags",
        type: "group",
        gender: "women",
        children: [
          "Handbags",
          "Tote Bags",
          "Satchel Bags",
          "Top Handle Bags",
          "Laptop Bags",
          "Backpacks",
          "Sling Bags",
        ],
      },
    ],
  },
  {
    name: "Accessories",
    slug: "accessories",
    type: "department",
    order: 4,
    children: [
      "Wallets",
      "Belts",
      "Card Holders",
      "Keychains",
      "Passport Holders",
      "Gloves",
      "Leather Accessories",
    ],
  },
  {
    name: "Home & Living",
    slug: "home-living",
    type: "department",
    order: 5,
    children: [
      "Leather Home Decor",
      "Cushions",
      "Storage Boxes",
      "Desk Accessories",
      "Leather Trays",
    ],
  },
  {
    name: "Collections",
    slug: "collections",
    type: "department",
    order: 6,
    children: [
      "Celebrity Leather Jackets",
      "Best Sellers",
      "New Arrivals",
      "Premium Collection",
      "Limited Edition",
      "Handmade Collection",
      "Suede Collection",
    ],
  },
  {
    name: "Custom Made",
    slug: "custom-made",
    type: "department",
    order: 7,
    children: [
      "Custom Jacket Order",
      "Custom Leather Apparel",
      "Custom Bags",
      "Made-to-Measure",
    ],
  },
  {
    name: "Sale",
    slug: "sale",
    type: "department",
    order: 8,
    children: [
      "Men's Sale",
      "Women's Sale",
      "Bags Sale",
      "Accessories Sale",
    ],
  },
];
